### ISSUE TITLE
Use AWS Rule for detecting drifts instead of lambda

### ISSUE THREAD

**Issue by haimlit** [cdklabs/cdk-drift-monitor#52]
AWS Config apparently has a rule for drift detection:

https://docs.aws.amazon.com/config/latest/developerguide/cloudformation-stack-drift-detection-check.html

Ideally the lambda should be replaced with:
- AWS config rule.
- CloudWatch event to log the rule resource compliance.
- A metric filter to alarm on non-compliant resources.

Possible breaking changes:
- AWS rule can work either on a specific resource identifier, or on resources with a specific tag. That might mean that stackNames can't be supported, as the construct needs to add a tag to the given stacks.
- AWS Config rules have a limited set of frequency, as opposed to the more flexibility currently provided in `runEvery`.

**Comment by rob3c** [comment]
I'm just bumping the thread since I'm not a fan of aggresive action bots. But maybe the linked PR has been merged, so this can be closed anyway?

**Comment by rob3c** [comment]
Another anti-bot bump
